"""create table1

Revision ID: f00f20317821
Revises: 
Create Date: 2024-03-11 12:02:14.706041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00f20317821'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_username', sa.String(), nullable=False),
    sa.Column('teacher_link', sa.String(), nullable=True),
    sa.Column('teacher_teleg_fullname', sa.String(), nullable=False),
    sa.Column('teacher_ref', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id'),
    sa.UniqueConstraint('teacher_ref'),
    sa.UniqueConstraint('teacher_username')
    )
    op.create_table('hardtasks',
    sa.Column('tasks_photo', sa.String(), nullable=True),
    sa.Column('tasks_text', sa.String(), nullable=True),
    sa.Column('number_hard_task', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('teacher_ref', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['teacher_ref'], ['teachers.teacher_ref'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('tasks_photo', sa.String(), nullable=True),
    sa.Column('tasks_text', sa.String(), nullable=True),
    sa.Column('number_task', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('solved', sa.Integer(), nullable=False),
    sa.Column('teacher_ref', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['teacher_ref'], ['teachers.teacher_ref'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_teleg_fullname', sa.String(), nullable=False),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.Column('teacher_ref', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['teacher_ref'], ['teachers.teacher_ref'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('homeworks',
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('id_hardtask', sa.Integer(), nullable=True),
    sa.Column('answer_user', sa.String(), nullable=True),
    sa.Column('solved_homework', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_hardtask'], ['hardtasks.id'], ),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    op.drop_table('user')
    op.drop_table('tasks')
    op.drop_table('hardtasks')
    op.drop_table('teachers')
    # ### end Alembic commands ###
